version: '3.9'

# Separation of concerns
# Separation of lifecycles / lifecycle awareness
services:
  db:
    image: arangodb:3.9.2
    ports:
      - 8529:8529
    container_name: db
    environment:
      - ARANGO_ROOT_USER=root
      # Docker secrets
      # https://docs.docker.com/engine/swarm/secrets/
      - ARANGO_ROOT_PASSWORD=openSesame
    healthcheck:
      test: curl -f -u root:openSesame http://localhost:8529/_api/version || exit 1
      timeout: 5s
      interval: 10s
      retries: 10

  app:
    build:
      context: ./codex
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080" 
